version: "3.9"
services:
  db:
    image: postgres:15
    container_name: muhasebe-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: muhasebe
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d muhasebe"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: muhasebe-backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # Geliştirme modunda canlı kod için (isteğe bağlı):
    # volumes:
    #   - ./backend/src:/app/src

volumes:
  db_data:
